# Generated by Django 6.0 on 2025-12-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_event_complaint_flat_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
